{"posts":[{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"everytime i run pytest now nothing happens what should i do","answers":[{"text":"hi joshua could you please try testing individual files by 'python3 -m pytest lt test file name gt ' and tell me what happens afterwards","theta":1,"count":0},[{"text":"when i try python3 -m pytest test_count.py or python3 -m pytest count.py it looks like the image above","theta":1,"count":0}],[{"text":"hi mr park pytest appears to be working on number_list and fib but not for count.py when using pytest for count.py it says collecting 0 items and just waits","theta":1,"count":0},[{"text":"hi the error seems most likely to be with pytest and pytest-mock being outdated although there could be many other possible reasons . could you please re-installing pytest and pytest-mock to the latest version for python3.6 by doing 'pip3 install pytest' and 'pip3 install pytest-mock' just for a double check the versions i currently have are pytest-3.6.0 and mock-1.10.0. please let me know if this doesn't solve the issue in which case i might have to inspect your source code .","theta":1,"count":0},[{"text":"hi i did the pip3 installs and after have versions pytest-3.4.2 and mock-1.7.1 still the same issue","theta":1,"count":0},[{"text":"okay then could you please push your current work to github so that i may inspect it and see what is going on and please tell me your github username so that i could locate it asap.","theta":1,"count":0},[{"text":"my github username is yveljj","theta":1,"count":0},[{"text":"hi joshua after inspecting your code it seems like you have an 'infinite loop' inside your code. please try to rectify this issue by being careful of where you are incrementing your counter 'j'.","theta":1,"count":0},[{"text":"ok thanks","theta":1,"count":0}]]]]]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"when i run pytest it stays like this and doesn't show any result i 've put the if __name__ '__main__' statement to prevent breaking and does the 25 mean i get 25 for this task or it has done 25 testing","answers":[{"text":"your solution to fibonacci is very inefficient which is why the tests are hanging. note that python has implemented at 1000 default limit on recursion depth. your solution is incapable of calculating very large kth fibonacci terms. try utilise the dictionary to reuse already calculated terms in your solution. percentage should reflect total tests which have been completed not marks.","theta":1,"count":0},[{"text":"regarding the percentage does that mean that when running pytest it should say 100 if no errors came up thanks","theta":1,"count":0},[{"text":"when a test fails it will pop out in output in red text. if not you passed them all don't focus on the percentages.","theta":1,"count":0}]],[{"text":"ok get it. thanks","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"does pytest test our program to see if we programmed correctly i ask because i run pytest and it says '12 passed' but when i look at the percentages next to each test file some its 25 33 and 100 for count.py fib.py test_number_list respecively. wondering if that's how it is meant to be or my program is still wrong thank you","answers":[{"text":"hi aran the 's are like a progress bar indicating how many of the test cases you have passed so far - so intermediary numbers do not matter as long as you acquired 100 in the end. and if it says you have passed all the test cases without any errors then you have congrats d","theta":1,"count":0},[{"text":"sweet thanks","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"i was stuck here . and wondering what to do with it.","answers":[{"text":"hi yuqin the lab starter code for lab02 is also available for direct download from the 'labs' page. since you may be in a hurry only an hour to go until it's due please download from there as an emergency measure but also please make sure to create your own git repo on github and push your work to there by 11.59pm.","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"hi are we allowed to use list function like list.reverse ... for number_list task","answers":[{"text":"list.reverse reverses in place and returns nothing. for a one line solution it is tough. try the inbuilt reversed function which you can combine with list inbuilt function. alternatively use slicing.","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"the more robust test causes all three types of the count tests to fail but passes all tests on the old count_test script. in the new test script the characters were added onto the third string. from the error messages it seems my program interprets these 3 chars as one char hence the length of the dictionary i used was 2 less. currently my code checks if the char is in the dictionary if not it appends to the dictionary. then the key's value is incremented by 1. i am wondering if this was intentionally done if so some guidance into solving this issue is much appreciated.","answers":[{"text":"hi arthur i am really sorry about the confusion - i really shouldn't have included the apostrophe in the test script because it is being interpreted differently on different editors amp text displays. could you please try clicking 'download' directly from the labs page instead of opening it up on webcms and copy-pasting if it does not solve the problem please let me know i will make a fix to the test script.","theta":1,"count":0},[{"text":"i have tested your solution the chars now show up as a regular apostrophe and is able to pass the tests thank you.","theta":1,"count":0}],[{"text":"ah also it is okay if your code has passed the old test_count script you do not need to test it on the newer one. the more 'robust' test script doesn't refer to how thorough the testing is but actually to the fact that it allows for different ordering among the characters that have the same count - so in fact it's a more generous version of the old test.","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"what does it mean by write code to accept user input do i not use input","answers":[{"text":"try using if __name__ '__main__' and place your input and print statements below. make sure this is define outside the fib_sequence function.","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"i have set the python3 as python3.6 but how could i install the pytest i have tried 'pip3 install pytest'","answers":[{"text":"what happens when you try pip3 install pytest","theta":1,"count":0},[{"text":"it says 'successfully installed atomicwrites-1.1.5 attrs-18.1.0 more-itertools-4.2.0 pathlib2-2.3.2 pluggy-0.7.1 py-1.5.4 pytest-3.7.1 setuptools-40.0.0 six-1.11.0' in the end when i use 'python3 -m pytest' it says 'no module named pytest'","theta":1,"count":0},[{"text":"try creating a virtual environment like so while inside your lab02 folder gt virtualenv --python python3.6 myenvironment activating it gt source myenvironment/bin/activate installing all packages defined inside the requirements file gt pip3 install -r requirements.txt edit please read new instructions","theta":1,"count":0},[{"text":"it works now thank you","theta":1,"count":0}]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"i can't run pytest. it shows bash pytest command not found. i downloaded the packages also.","answers":[{"text":"please read https //webcms3.cse.unsw.edu.au/comp1531/18s2/foru...","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"when i run pytest or test_count.py i get this error test_count.py unhandled exception occurred while testing test_count traceback most recent call last file /usr/lib/python2.7/dist-packages/logilab/common/pytest.py line 447 in testfile options self.options outstream sys.stderr file /usr/lib/python2.7/dist-packages/logilab/common/pytest.py line 763 in __init__ testloader nonstricttestloader file /usr/lib/python2.7/unittest/main.py line 77 in __init__ self.module __import__ module file test_count.py line 16 syntaxerror non-ascii character ' xe2' in file test_count.py on line 16 but no encoding declared see http //python.org/dev/peps/pep-0263/ for details the program seems to work i'm just not sure why the test program throws an error any help would be much apprecaited","answers":[{"text":"hi brendan please make sure that you are using python 3.6 currently you are using python 2.7 . if you have not installed python 3.6 please install it if you do have it installed and if it is throwing the same error please try running the pytest by python3 -m pytest","theta":1,"count":0},[{"text":"i have python 3.6 installed but when i run python3 -m pytest i get /usr/bin/python3.6 no module named pytest do i need use python3 to install pytest thanks for your reply","theta":1,"count":0},[{"text":"yup in that case try 'pip3 install pytest' to download pytest for python 3.6","theta":1,"count":0},[{"text":"it then runs the tests as python 3.5.2 and crashes when it sees the f' as you know is only a feature of 3.6 is there a way i can force it to run as python 3.6 and not 3.5.2 i've tried python3.6 -m pytest","theta":1,"count":0}]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"i'm confused as to what the error is in my count_char_ordered","answers":[{"text":"hi krittika the first error says that your program printed out w 1 r 1 ... etc. whereas the expected output is l 3 o 2 ... etc. count_char_ordered should print out the characters in the descending order of counts but your function doesn't seem to do this correctly. so please try to understand the current behaviour of your program by testing the function manually with user input. for the second error it seems like you haven't stored any new answers to fib_dict the error says that fib_dict 4 did not work because it doesn't have any value associated with the key '4' yet. to resolve this issue try to consider two cases 1 when your fib_dict does not contain the key 'num' and 2 when your fib_dict does contain the key i.e. when it already has the answer to fib_sequence num . in the first case you should compute the value of fibonacci number using recursion and store that value into fib_dict so that you won't have to compute it again later. in the second case you should simply return the value stored in fib_dict corresponding to 'num' you already have implemented this part . please let me know if you are still having issues also there are previous forum questions amp answers on this - so may be refer to those as well . cheers d","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"hi guys getting the following errors for all three count.py exercises when i run the pytests please help. thanks","answers":[{"text":"hi jack please try installing the pytest mocker used in the autotest again with 'pip3 install pytest-mock' within your virutal environment.","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"for count.py i have several questions 1. which final output type is needed for pytest dictionary set or list 2. need i write print command inside each function 3. i can print what is needed when tested manually since i added print command in my code but i can't pass pytest the error is below need help","answers":[{"text":"hi ziwei as described in the main announcement for the output you must print each character in a separate line. and each line should contain the character and its count separated by a single space. please refer to the announcement for the example output. so instead of returning anything your function is expected to print the results. and the error above is occurring because your code only printed a single line of output whereas the test expects exactly 13 lines. this issue should be resolved as well if you follow the output format explained above.","theta":1,"count":0},[{"text":"thanks for the reply d so is that mean i need to add something like print command to print out the outputs like 13 lines","theta":1,"count":0},[{"text":"yup that's right. try 'print char count ' where 'char' is a variable representing the character and 'count' is the variable representing how many times the character has appeared in the text.","theta":1,"count":0},[{"text":"it works and pass the test thank you very much d","theta":1,"count":0}]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"i'm not sure what this error means. any help appreciated","answers":[{"text":"hi ravija please try 'pip3 install pytest-mock' and try to run the pytest again. it seems like pytest-mock wasn't installed correctly.","theta":1,"count":0},[{"text":"thanks so much it works now","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"for some odd reason the assert tests in pytest for count.py are picking up different output compared to output produced by python when run manually. particularly the letter count for every letter seems to be doubled. it works fine when run manually but the asserts keep picking up incorrect output. can someone please advice.","answers":[{"text":"hi farhan could you please include a screenshot of the outputs so that i can figure out what the actual issue may be thanks","theta":1,"count":0},[{"text":"the first image shows output when i run my program manually. the second image shows the diff output picked up by pytest. the left set which i believe is my output is different from the output from the first image.","theta":1,"count":0},[{"text":"hm... okay here's my guess. are you by any chance calling the 'count_char' function anywhere inside your count.py this could be the cause of the issue if you are not initialising your counting dictionary at the start of the function. this would mean that when pytest is executed your count.py would be loaded and the function would be called on loading setting the counts of the characters to be what they should be but when the pytest actually calls the function for testing you will be incrementing the counts from already existing ones and hence the reason for the double count. so to solve this please simply remove any function calls within count.py and please make sure that you are initialising your counting dictionary at the start of each function call dict_name however if my guess was wrong quite likely please either send me a copy of your code via email or push your current work to github so i may inspect it further. d cheers ian.","theta":1,"count":0},[{"text":"hi park yes it is as you suspected. i've been initialising my dictionary outside my function all this time this was pointed out to me by my tutor as i had my lab today so i guess i owe both of you. we're all good now. thanks for taking your time with this","theta":1,"count":0}]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"count_char_ordered pytest problem my program ranked them correctly according to the times that char appears but when it comes to the chars that appear the same times my order is different from the pytest's outcome and so i cant pass it.","answers":[{"text":"hi xiang please try replacing your test_count.py file with the file provided in 'more robust test for count.py' listed in the labs section for week 2 if you are having issues with different ordering mechanism used by the pytest. please let me know if you are still experiencing issues. cheers ian","theta":1,"count":0},[{"text":"it works cheers","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"pytest not running past session starting running in vlab from my mac new stuck on test_fib.py indefinitely as pictured below. i have triple checked all my functions and they all run as they should and downloaded the more robust test file for count.py. not sure why this is happening.","answers":[{"text":"hi yutian it is most likely that your implementation of fibonacci is not efficient enough. please try to utilise the given dict fib_dict in order to avoid re-computing the same fibonacci number when the function is called several times with the same parameter. for more explanation please refer to previous forum question amp answers because this has been addressed numerous time already. but if you are still having issues please let me know. d cheers ian","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"does anyone know how to install pytest on mac","answers":[{"text":"yup just try 'pip3 install pytest' assuming that you have pip3 installed . but for the lab02 you should try to follow the instructions for installing pytest and other dependencies on virtual environment pip3 install -r requirements.txt .","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"i'm getting an error on test_count.py in the pytest program lab02/lib/python3.5/site-packages/py/_path/local.py 668 in pyimport __import__ modname e file /mnt/c/users/ellen/cs1531-lab02/test_count.py line 83 e o_buffer f' char count n' e e syntaxerror invalid syntax in count.py i am printing the output as a string one line at a time and the output looks correct if i test manually. i'm not sure if this is because of something my output is causing having a bit of trouble with debugging it. any suggestions","answers":[{"text":"if anyone else is stuck on this after installing python 3.6 i had to run virtualenv lab02 -p python3.6 to get the virtual env to set up with 3.6 otherwise it still defaulted to python3.5","theta":1,"count":0},{"text":"hi ellen for this course you are required to use python version 3.6 exactly. currently you are using python3.5 - which does not support the f'...' feature utilised in the pytest file. so please make sure that you have installed python v3.6 not python 3.7 either because it does have some features not in 3.6 . please let me know if you are still having issues after installing python 3.6 d cheers ian.","theta":1,"count":0},[{"text":"hi ian i'm now getting another error fixture mocker not found. the venv is in python 3.6. i have run through the entire setup process again to make sure i did everything right.","theta":1,"count":0},[{"text":"hi ellen please try to install pytest-mock again within the virtual environment i believe the autotest is trying to use an outdated version of a library gt gt pip3 install pytest-mock please let me know if you still have any issues after installing it. d","theta":1,"count":0},[{"text":"thanks it worked d","theta":1,"count":0}]]],[{"text":"ok thanks ian","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"problem for home device setting when i run it shows the path /usr/bin/python3 from --python /usr/bin/python3 does not exist so i run virtualenv --python /usr/bin/python venv it works fine but when i run pytest it shows please help thank you","answers":[{"text":"hi chenghe the error is occurring because the f'...' syntax newly introduced in python v3.6. please make sure that you are using python3.6 for this course not 3.5 as you have at the moment and not v3.7 either because it also contains some features not provided in 3.6 . please let me know if you are still having issues after installing it. d","theta":1,"count":0},[{"text":"thanks for your help i have done this lab in school computer.","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"for count.py does the order letters with the same count that are printed out matter here's an example of what my program prints using helloworld this is the example written in the lab if so what pattern should characters of the same count follow edit pytest keeps on crashing when i run the test for fibonacci i have already included the if statement not sure what i'm doing wrong there...","answers":[{"text":"hi angela yes you are right you may print out characters with the same count in any order - except the pytest does not account for it - so i have put up a more flexible and proper test on the labs page please copy and replace your test_count with the new one. or instead you can just ask your tutor to check the outputs manually if you prefer that option. actually pytest expects the character that appeared first in the text to come before the other character in the results if they have the same count - so you could try implementing your code this way . also for fibonacci it is probably crashing because you forgot to utilise the fib_dict dictionary - without this the program will be very inefficient and will not be able to handle large inputs such as 100 or 1000. try to think of fib_dict as a memo for storing question-answer pairs. for example fib_dict 0 0 1 1 2 1 tell us that we already know the answer for the questions fib_sequence 0 fib_sequence 1 and fib_sequence 2 - which are 0 1 1 respectively. so to optimise your function you can do the following 1. if you already know the answer to fib_sequence num the just return the answer stored in fib_dict 2. otherwise compute the answer by recursion answer fib_sequence ... fib_sequence ... and store that answer in fib_dict fib_dict ... ... - so that you won't have to compute it again - and return that answer. in this way if you already have computed the answer for a question then you do not have to compute it again and only have to return the answer we have stored in fib_dict. this will improve the performance of your function dramatically. the ...'s are left for you to fill out d","theta":1,"count":0},[{"text":"thanks so much for the detailed response","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"quick question - when running the tests in the virtual environment the asserts are output as comparisons between 2 sets left and right . which set represents my program output left or right also i think the asserts output different results compared to whats output when run manually. please advice.","answers":[{"text":"hi farhan for this pytest the ones on the left represents your output the ones on the right are the expected. regarding the second question could you please attach some screenshots of the outputs both from the 'asserts' and from manual running i am not so sure by just reading the words but my guess is that you have things like ' n' in the assert outputs - but these just denote a newline in your output. please let me know if if you think it's something else. d","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"traceback most recent call last file count.py line 335 in lt module gt count_char text1 file count.py line 283 in count_char print u2019 letter_list ' u2019' unicodeencodeerror 'latin-1' codec can't encode character ' u2019' in position 0 ordinal not in range 256 -----python won't recognise ' character. please advice.","answers":[{"text":"hi farhan. yup that is a mistake on my part - which is happening only to some students for some reason please try wrapping the string for text1 with double quotation marks instead of single-quotes ' ' and re-write the single-quote in ... won't ... by removing it and adding it back using your keyboard not copy-paste . so change ' i felt happy because i saw the others were happy and because i knew i should feel happy but i wasn t really happy ' to i felt happy because i saw the others were happy and because i knew i should feel happy but i wasn't really happy thanks ian","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"runtimeerror maximum recursion depth exceeded is the error i keep getting when trying to run fibonacci.py could someone please help me","answers":[{"text":"note that python will limit how deep your recursion can go to prevent unlimited recursion which is a big problem in itself. so to calculate fibonacci for very large numbers it is wise to utilise the dictionary in some way to reduce the amount of computations required for these very large numbers.","theta":1,"count":0},{"text":"i think that may mean your function can't stop recursing meaning the condition for stopping your function from recursion isn't met. i'm not sure if what i'm doing is right as pytest doesn't work for fibonacci for me but i guess a hint is to copy the formula they gave us in the comments of the file","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"the requirements of count.py are not clear enough for example spaces and commas are not counted based on the output example from https //webcms3.cse.unsw.edu.au/comp1531/18s2/reso... . however spaces and commas are counted in test_count.py . should we return a list dictionary or just print the results from our function i keep getting errors from pytest for count.py but it works fine manually.","answers":[{"text":"hi matthew i am really sorry about the confusion - i believe there was some miscommunication among the admins. the correct example input amp output are do count_char_ordered helloworld output l 3 o 2 h 1 e 1 w 1 r 1 d 1 1 space and commas should be counted as well basically every character should be counted if there are any. and you shouldn't just return the dictionary but instead print the results as shown by the example output every character must be printed in a separate line along with its count. please let me know if you continue to have issues with the exercise. regards ian.","theta":1,"count":0},{"text":"same issue here. it works fine manually but pytest keeps complaining. can someone please advice.","theta":1,"count":0},[{"text":"i'm not sure what your issue is but one thing you have to do it print every item in your dictionary on a new line.","theta":1,"count":0},[{"text":"hi alex yeah my code updates my dictionary and then proceeds to print every dictionary item on a new line with the appropriate count. i can't seem to figure out where my output is going wrong. i suspect that maybe it is the order in which the letters are printed that might be causing the asserts to fail. however for the first exercise order doesn't need to accounted for so i'm not really sure.","theta":1,"count":0},[{"text":"use pytest -vv to see what is actually different from the two outputs.","theta":1,"count":0}]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"oserror reading from stdin while output is captured are we supposed to write code to accept user input in fibonacci.py when i run pytest with code to accept user input i get the above error. when i run pytest without it runs fine.","answers":[{"text":"the issue is indeed due to your fibonacci.py asking for a user input when the pytests are running. however there is a way to keep that input-reading code while letting the test work. try placing your input-reading code under this if statement in fibonacci.py if __name__ '__main__' read input print this means that only run the body of the code under the if statement only when fibonacci.py file is directly executed python3 fibonacci.py - otherwise this part of the code would not run and hence wouldn't interfere with pytest either. d","theta":1,"count":0},{"text":"i am facing the same issue. it works fine when i run it manually. however pytest gives me the same error as above.","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"are we permitted to use string methods for this weeks exercises","answers":[{"text":"yup yes you are d","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"hi what is the output format for count_char count_char_insensitive and count_char_ordered also when i run pytest i get this fixture 'mocker' not found message. what does it mean thanks","answers":[{"text":"hi igansius for count.py exercises you should print information about each character in a separate line and the information about a character should be the character followed by its count with a space in between . so if you have five h's three e's and ten a's a possible output could be h 5 e 3 a 10 of course for count_char_ordered the output should be ordered by the character count. also if you are getting a message regarding the mocker please make sure that you have installed all the dependencies in the requirements.txt as shown in the lab instructions . if you do not think that this is the issue please let me know. cheers ian","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"how do we run individual test on our files please advice. thanks","answers":[{"text":"hi farhan please try 'pytest lt test file name gt ' e.g. pytest test_count.py to test your solutions. if that does not work sometimes it doesn't please try 'python3 -m pytest lt test file name gt ' instead. d","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 02","salience":0.5,"theta":1},{"name":"lab 02 - python data structures","salience":0.5,"theta":1}],"question":"hi when i run each test individually no issues come up however when i run pytest it hangs at test_fib.py also how are they supposed to show up when the tests are passed with pytest thanks","answers":[{"text":"hi sophie you may implement the function using binet's formula as an extension woohoo but for this lab exercise you must use recursion to complete the lab. furthermore binet's formula may not actually be faster try it yourself unless further optimisations are made. about the input/print bit yes the pytest would crash normally due to the input function being called while the test is running. however there is a way to keep the input/print bits in the code while not interrupting the pytest. try wrapping your input/print bits under the following if statement if __name__ '__main__' read input compute fib print output it means you should only run the block of code under the if statement only if the file was executed directly from the terminal and not indirectly through other files e.g. pytests . d","theta":1,"count":0},{"text":"hi sophie although i cannot say for sure this is a common problem that occurs with the exercise when the students forget to optimise the algorithm using the dictionary 'fib_dict' provided appropriately. please be warned that the function will behave very slowly without using it - and thus the test will take forever to run waiting for your function to complete it could actually take more than few trillion years . here's a little hint if you follow the execution of fib_sequence 100 you will realise that calling fib_sequence 100 will call fib_sequence 99 and fib_sequence 98 . but when fib_sequence 99 is called it will call fib_sequence 98 too so in fact fib_sequence 98 will be computed twice in a naive implementation - hence inefficiency occurs. this kind of redundant computation occurs even more frantically as you continue to follow down the execution of fib_sequence 100 e.g. fib_sequence 2 will be called 135301852344706746049 times in total . so please have a think about how you could avoid repeating same computations using 'fib_dict'. by the way for your interest the name of this technique is called 'memoisation'. hope this helped. d","theta":1,"count":0},[{"text":"hi su just read up on memoisation that helped a lot. thanks for the detailed explanation","theta":1,"count":0}]]}]}