{"posts":[{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"error 404 not found i did run using python3 run.py but i got this error instead the requested url was not found on the server. if you entered the url manually please check your spelling and try again. anyone can help me with this problem thanks","answers":[{"text":"hi mikamocha have you set up the route for an empty url by any chance please check if you have something like this app.route '/' def index pass the app.route '/' above a function any name is good is what you need to actually make the url http //127.0.0.1 5000/ valid.","theta":1,"count":0},[{"text":"i am getting the same problem sometimes idk why can somebody help","theta":1,"count":0},[{"text":"hey dhruv to help with this issue could you describe how you are set up using vlab ssh or running locally . also ensure that it is indeed not working for a simple example like ian's above one otherwise it would have to do with how you wrote it rather than your set up. lastly attempt to add or remove the slash at the end of your url on the browser and checking if that may fix it","theta":1,"count":0}]],[{"text":"nope i fixed my app.route when i ran it on my terminal.","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"adding collaborator i want to add my partner as a collaborator to the repo so we can work on the code together but i cannot since i do not own the repo. is there a way around this","answers":[{"text":"hi arthur if you are asking about the week 6/7 lab the lab must be done individually - so no collaborators","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"how do add in a check for if time is valid or not in lab06-07","answers":[{"text":"invlaid time is anything that is not a non negative number. you can check for this in routes after retrieving from request.form","theta":1,"count":0}]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"it worked fine in cse lab but when i got home. it gave me this error have no idea how to fix it. please have a look ty","answers":[{"text":"hi jiahao the error message says address already in use - this usually happens when you already have another process running on your machine that is using the same port number as the one your python program is trying to use. so a quick solution to this is to simply change the port number for your program. try app.run port 8181 debug true . cheers","theta":1,"count":0},[{"text":"hi i inserted the line app.run port 8181 debug true in routes.py beneath from app import app but i still keep encountering the 'address is already in use' error are there any ways i can fix this thanks","theta":1,"count":0},[{"text":"please try to avoid doing app.run ... in the routes.py because we have separated the starting code into three different files routes run server so that each of them can serve a distinct purpose. so instead app.run should be located in run.py and in fact there should already be one in that file so you only need to modify it a bit to resolve your issue. please tell me if this would still not solve your issue.","theta":1,"count":0},[{"text":"ah right yep that makes sense. thanks it's working now","theta":1,"count":0}],[{"text":"hi i inserted the app.run ... into run.py and i'm still getting the same error. how can i fix this thanks.","theta":1,"count":0},[{"text":"one thing you could try first is to using different port numbers 8080 8081 8082 ... or even restarting your machine or killing the python processes running in the background but if none of those work the easiest way for me to figure out the problem would be to check your code on github if you could put it up on there.","theta":1,"count":0},[{"text":"i have tried different port numbers and i'm not permitted to kill the python processes. i'm worried this same issue will happen for my group project. edit after i restart my computer i can run flask 2 times before the same error occurs. also when i go to localhost 5000 someone else's interest calculator is there instead","theta":1,"count":0},[{"text":"hi it took me a while to experiment with things. i realised that it is very easy to encounter such issues when you are running your flask app on the cse machines or via vlab because the ports are being shared across multiple users as far as i can see it may be false or are not being recycled properly. so i would recommend you to run your flask programs on your own device to avoid such issues.","theta":1,"count":0}]]]]]]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"can someone helps me figure out why this happens and how to fix this. thank u. gt","answers":[{"text":"yup please read the previous post or quick fix do app.run port 5001 debug true in run.py .","theta":1,"count":0},[{"text":"ty gt","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"unable to git clone the repo. not sure what i'm doing wrong here","answers":[{"text":"hmm the repo does indeed exist you are a collaborator and i am able to clone it myself. you are using the https link however you are getting an error before you can even authenticate. my guess is you have set it up to automatically sign in but with a different github account than the collaborator with a quick search you may be using osxkeychain to do that if that rings a bell you might to disable/change that","theta":1,"count":0},[{"text":"thanks i used the ssh key instead and it seemed to work.","theta":1,"count":0}]]},{"intent":"assignments","courseCode":"COMP1531","tags":[{"name":"forums","salience":0.5,"theta":1},{"name":"tuts and labs","salience":0.5,"theta":1},{"name":"week 6","salience":0.5,"theta":1},{"name":"week 06_07 lab - simple interest calculator","salience":0.5,"theta":1}],"question":"hi. i'm trying to use html and flask at home. but when i open html at chrome some parts of it don't work. even when i use the example given in the lecture it can not work properly as in the lecture. v-lab doesn't work also. is there something wrong or i should download something","answers":[{"text":"opening html as google chrome is not the same as running a web application. you are essentially viewing a template of your web app without any real functionality. you will need to use python3 run.py to start your server which will then provide you a link to the web-app. i would suggest having a look at how run.py is implemented.","theta":1,"count":0},[{"text":"by the way i got this error. do i need to solve this environment production warning do not use the development server in a production environment. use a production wsgi server instead.","theta":1,"count":0},[{"text":"it is fine.","theta":1,"count":0}]],[{"text":"okay i will try thank you","theta":1,"count":0}]]}]}